### ISSUE TITLE
suggestions re: select()

### ISSUE THREAD

**Issue by jrosen48** [making-data-science-count/MEGABITESS#2]
looking at code like this in `combine-and-describe-data`:

```{r}
Q1_1 <- comment %>%
  select("Survey","Q1_1")%>%
  count()
```
```{r}
Q1_2 <- comment %>%
  select("Survey","Q1_2")%>%
  count()
```

Two suggestions:

1. Do not quote the names of variables in `select()` - instead, just type the name, e.g. `select(Survey, Q1_1)`
2. If there is not text in between the R code, you can drop the additional chunk, e.g. the above (also not quoting the names) could be:

```{r}
Q1_1 <- comment %>%
  select(Survey, Q1_1)%>%
  count()

Q1_2 <- comment %>%
  select(Survey, Q1_2)%>%
  count()
```

**Comment by mjmann983** [comment]
remove of the quotation marks for the select() coding done and working.

**Comment by jrosen48** [comment]
I think point 2 above is not addressed

**Comment by mjmann983** [comment]
I think it should be good to go now. I pushed it

**Comment by jrosen48** [comment]
this is minor and doesn't cause a problem with the code, but these are still in separate code chunks, see below:

![Screen Shot 2020-10-14 at 9 44 10 AM](https://user-images.githubusercontent.com/4596214/95997478-d23e8180-0e01-11eb-84c7-7adfec45d207.png)

you can just include these in one chunk, like this:

![Screen Shot 2020-10-14 at 9 45 09 AM](https://user-images.githubusercontent.com/4596214/95997614-f4380400-0e01-11eb-8aad-afccc53b94bf.png)

**Comment by mjmann983** [comment]
all corrected and posted to the MEGA:BITESS slack

**Comment by jrosen48** [comment]
WTG MM. Let's touch base about the next steps on this analysis after the SIGSCE submission.
